/**
 *
 *  Confirm.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Confirm.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::test;

const std::string Confirm::Cols::_useruuid = "useruuid";
const std::string Confirm::Cols::_txuuid = "txuuid";
const std::vector<std::string> Confirm::primaryKeyName = {"useruuid","txuuid"};
const bool Confirm::hasPrimaryKey = true;
const std::string Confirm::tableName = "confirm";

const std::vector<typename Confirm::MetaData> Confirm::metaData_={
{"useruuid","std::string","varchar(100)",100,0,1,1},
{"txuuid","std::string","varchar(100)",100,0,1,1}
};
const std::string &Confirm::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Confirm::Confirm(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["useruuid"].isNull())
        {
            useruuid_=std::make_shared<std::string>(r["useruuid"].as<std::string>());
        }
        if(!r["txuuid"].isNull())
        {
            txuuid_=std::make_shared<std::string>(r["txuuid"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            useruuid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            txuuid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Confirm::Confirm(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            useruuid_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            txuuid_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

Confirm::Confirm(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("useruuid"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["useruuid"].isNull())
        {
            useruuid_=std::make_shared<std::string>(pJson["useruuid"].asString());
        }
    }
    if(pJson.isMember("txuuid"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["txuuid"].isNull())
        {
            txuuid_=std::make_shared<std::string>(pJson["txuuid"].asString());
        }
    }
}

void Confirm::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            useruuid_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            txuuid_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

void Confirm::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("useruuid"))
    {
        if(!pJson["useruuid"].isNull())
        {
            useruuid_=std::make_shared<std::string>(pJson["useruuid"].asString());
        }
    }
    if(pJson.isMember("txuuid"))
    {
        if(!pJson["txuuid"].isNull())
        {
            txuuid_=std::make_shared<std::string>(pJson["txuuid"].asString());
        }
    }
}

const std::string &Confirm::getValueOfUseruuid() const noexcept
{
    const static std::string defaultValue = std::string();
    if(useruuid_)
        return *useruuid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Confirm::getUseruuid() const noexcept
{
    return useruuid_;
}
void Confirm::setUseruuid(const std::string &pUseruuid) noexcept
{
    useruuid_ = std::make_shared<std::string>(pUseruuid);
    dirtyFlag_[0] = true;
}
void Confirm::setUseruuid(std::string &&pUseruuid) noexcept
{
    useruuid_ = std::make_shared<std::string>(std::move(pUseruuid));
    dirtyFlag_[0] = true;
}

const std::string &Confirm::getValueOfTxuuid() const noexcept
{
    const static std::string defaultValue = std::string();
    if(txuuid_)
        return *txuuid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Confirm::getTxuuid() const noexcept
{
    return txuuid_;
}
void Confirm::setTxuuid(const std::string &pTxuuid) noexcept
{
    txuuid_ = std::make_shared<std::string>(pTxuuid);
    dirtyFlag_[1] = true;
}
void Confirm::setTxuuid(std::string &&pTxuuid) noexcept
{
    txuuid_ = std::make_shared<std::string>(std::move(pTxuuid));
    dirtyFlag_[1] = true;
}

void Confirm::updateId(const uint64_t id)
{
}
typename Confirm::PrimaryKeyType Confirm::getPrimaryKey() const
{
    return std::make_tuple(*useruuid_,*txuuid_);
}

const std::vector<std::string> &Confirm::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "useruuid",
        "txuuid"
    };
    return inCols;
}

void Confirm::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUseruuid())
        {
            binder << getValueOfUseruuid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTxuuid())
        {
            binder << getValueOfTxuuid();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Confirm::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void Confirm::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUseruuid())
        {
            binder << getValueOfUseruuid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTxuuid())
        {
            binder << getValueOfTxuuid();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Confirm::toJson() const
{
    Json::Value ret;
    if(getUseruuid())
    {
        ret["useruuid"]=getValueOfUseruuid();
    }
    else
    {
        ret["useruuid"]=Json::Value();
    }
    if(getTxuuid())
    {
        ret["txuuid"]=getValueOfTxuuid();
    }
    else
    {
        ret["txuuid"]=Json::Value();
    }
    return ret;
}

Json::Value Confirm::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getUseruuid())
            {
                ret[pMasqueradingVector[0]]=getValueOfUseruuid();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTxuuid())
            {
                ret[pMasqueradingVector[1]]=getValueOfTxuuid();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getUseruuid())
    {
        ret["useruuid"]=getValueOfUseruuid();
    }
    else
    {
        ret["useruuid"]=Json::Value();
    }
    if(getTxuuid())
    {
        ret["txuuid"]=getValueOfTxuuid();
    }
    else
    {
        ret["txuuid"]=Json::Value();
    }
    return ret;
}

bool Confirm::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("useruuid"))
    {
        if(!validJsonOfField(0, "useruuid", pJson["useruuid"], err, true))
            return false;
    }
    else
    {
        err="The useruuid column cannot be null";
        return false;
    }
    if(pJson.isMember("txuuid"))
    {
        if(!validJsonOfField(1, "txuuid", pJson["txuuid"], err, true))
            return false;
    }
    else
    {
        err="The txuuid column cannot be null";
        return false;
    }
    return true;
}
bool Confirm::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Confirm::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("useruuid"))
    {
        if(!validJsonOfField(0, "useruuid", pJson["useruuid"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("txuuid"))
    {
        if(!validJsonOfField(1, "txuuid", pJson["txuuid"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool Confirm::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Confirm::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }

            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
